jv_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: JVUserBundle:Default:index }
    
jv_user_index:
    path:     /user/index
    defaults: { _controller: JVUserBundle:User:index }
